# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HKweb - Joomla en Magento frontend development
email: hans@hkweb.nl
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
google-tag-manager: GTM-NDTF7X
url: "http://hkweb.nl" # the base hostname & protocol for your site
twitter_username: hans2103
github_username:  hans2103

# Build settings
markdown: kramdown

exclude: ['css', '_scss']
exclude: ['fonts']
exclude: ['node_modules']
keep_files: ['_site/css']

social-icons:
  - title: Facebook
    url: https://www.facebook.com/hans2103
    class: facebook
  - title: Twitter
    url: https://twitter.com/hans2103
    class: twitter
  - title: Googleplus
    url: https://plus.google.com/+HansKuijpers
    class: googleplus
  - title: LinkedIn
    url: https://www.linkedin.com/in/hans2103
    class: linkedin
  - title: Behance
    url: https://www.behance.net/hans2103
    class: behance
  - title: Pinterest
    url: https://www.pinterest.com/hans2103/
    class: pinterest
  - title: GitHub
    url: https://github.com/hans2103
    class: github
  - title: LinkedIn
    url: http://www.slideshare.net/hans2103
    class: linkedin
